export const ActionType = {
  ADD_MOVIE: 'ADD_MOVIE',
  ADD_MOVIE2: 'ADD_MOVIE2',
  ADD_MOVIE3: 'ADD_MOVIE3',
  ADD_MOVIE4: 'ADD_MOVIE4',
  ADD_MOVIE5: 'ADD_MOVIE5',
  REMOVE_MOVIE: 'REMOVE_MOVIE',
  SWITCH_PAGES: 'SWITCH_PAGES',
};
