export const ActionType = {
  ADD_MOVIE: 'ADD_MOVIE',
  ADD_MOVIE2: 'ADD_MOVIE2',
  ADD_MOVIE3: 'ADD_MOVIE3',
  ADD_MOVIE4: 'ADD_MOVIE4',
  ADD_MOVIE5: 'ADD_MOVIE5',
  REMOVE_MOVIE1: 'REMOVE_MOVIE1',
  REMOVE_MOVIE2: 'REMOVE_MOVIE2',
  REMOVE_MOVIE3: 'REMOVE_MOVIE3',
  REMOVE_MOVIE4: 'REMOVE_MOVIE4',
  REMOVE_MOVIE5: 'REMOVE_MOVIE5',
};
